### ISSUE TITLE
conda/ mamba version conflicts

### ISSUE THREAD

**Issue by genio0815** [DerKevinRiehl/transposon_annotation_reasonaTE#1]
Hi,

when following the (conda style) installation procedure a lot of 
```
UnsatisfiableError: The following specifications were found to be incompatible with each other
```
pop up.

Even when changing the used version of python to  `python=3.9.2=hffdb5ce_0_cpython` as found in the previously used [transposon_annotation_reasonaTE.yml](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/blob/main/transposon_annotation_reasonaTE.yml) does not fix the issue.

Only easy (but untested) workaround is to stick to prior version and installation via mentioned yaml file

cheers

**Comment by DerKevinRiehl** [comment]
Hello genio0815,
thank you very much for your suggestion.

Could you please explain me, if this happened with mamba as well? With conda, is was reported for some users, as conda struggles with environment solving sometimes. (even though its same OS and conda version)

Could you tell me, from a users perspective, why you did not chose the recommended way using mamba? Its completely doable using conda (as mamba is installed via conda).

_Only easy (but untested) workaround is to stick to prior version and installation via mentioned yaml file_
Thats true, in the past I mentioned the installation procedure via yml file, but as I developed this github, I removed this option from the tutorial. Now its back there again.

**Installation using yml file (works for Linux64)**
```
wget https://raw.githubusercontent.com/DerKevinRiehl/transposon_annotation_reasonaTE/main/environment_yml/transposon_annotation_tools_env.yml
wget https://raw.githubusercontent.com/DerKevinRiehl/transposon_annotation_reasonaTE/main/environment_yml/transposon_annotation_reasonaTE.yml
conda env create -f transposon_annotation_tools_env.yml
conda env create -f transposon_annotation_reasonaTE.yml
```

Best regards and looking forward hearing back from you soon,
Kevin

**Comment by genio0815** [comment]
Hi,

I tried the mamba approach initially, but that failed with
```
Problem: nothing provides blast needed by transposon_annotation_tools_proteinncbicdd1000-1.0.0-1
```
and switched to the conda way, hoping that this pulls in blast from somewhere.

So, I guess adding a dependency on `blast`(as in the yml file; repeatmasker, repeatmodeler and genomictools I installed differently, but none of these depend on blast) and updating the installation instructions for python (it says python=2.7) could solve this.

cheers

**Comment by DerKevinRiehl** [comment]
Okay thank you very much.

 As different users report different errors for different ways, we offer three ways now, I guess most of the people should manage installing the software now using one of these. Thank you for your report!

Best regards,
Kevin
