### ISSUE TITLE
Issue with sinescan

### ISSUE THREAD

**Issue by macobam** [DerKevinRiehl/transposon_annotation_reasonaTE#25]
Hi Kevin, 

I've trying to run reasonaTE with a genome to identify TEs, but I've been thinking about a message that obtained when run sinescan tool, in some parts while the tool is running, appear in the screen the next message:

![image](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/assets/148499901/3370af60-29d5-48f6-9e4b-b9d459d7d20f)

Is it a problem? at the end, it says that the tool finished successfully

![image](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/assets/148499901/c3594cc3-ee38-4e1f-aba0-f78a7f0b200f)

Kind regards

**Comment by DerKevinRiehl** [comment]
Hello macobam,
the error message originates from the tool sinescan our software calls, but it is not written by us.

I guess it should be fine.

Best, Kevin
