### ISSUE TITLE
RepeatModeler version Error

### ISSUE THREAD

**Issue by Riccardo1274** [DerKevinRiehl/transposon_annotation_reasonaTE#27]
Good morning Kevin,
while running  "reasonaTE -mode annotate -projectFolder workspace -projectName project -tool repeatmodel", I got the following error:
Building database sequence_index:
  Adding sequence.fasta to database
Number of sequences (bp) added to database: 617 ( 1105955550 bp )
ERROR: The -pa parameter has been deprecated.  Please use the newer
      "-threads #" parameter which precisely controls the maximum
       number of simultaneous threads this program will use. Note that
       the -pa parameter previously controlled the number of simultaneous
       batches each run with rmblast using 4 threads, therefore -pa 4 could
       potentially have used up to 16 threads.  Keep this in mind when
       comparing runtime differences between versions.
I tried modifying your python scripts to replace the "-pa" parameter with "-threads" in "Dupmask", but I still got the same message.
I fixed it by removing repeatmodel and downloading (with conda) version 1.0.11, now it seems to work fine.
As your tool is really useful and well done, it would be nice to use the latest versions.
If you could tell me where I need to modify your python scripts, I would be very grateful.
Thanks in advance.

Kind regards,
Riccardo Rossi

**Comment by DerKevinRiehl** [comment]
Dear Riccardo,
thank you very much for your interest in our work.

A challenge with enabling latest versions is version incompatibility issues with other tools.
It would require not only to change the python code (as you did replacing -pa and -threads) but also the conda environment YML that I composed to work in this context.
It might be possible to use updated software versions, however there is a high chance that this conflicts with another tool.

If you want to try,  you can find all software packages and versions in the YML files.
https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/tree/main/environment_yml

Hope this can help a little,
Best regards, Kevin

**Comment by Riccardo1274** [comment]
Thank you for your reply and suggestion. I'll keep using the previous version of RepeatModeler as it worked.
Thanks again for developing this pipeline!
