### ISSUE TITLE
reasonaTE annotate interrupted: error 'File exists'

### ISSUE THREAD

**Issue by fantin-mesny** [DerKevinRiehl/transposon_annotation_reasonaTE#5]
Hi,
I was running reasonaTE (-mode annotate -tool all) and it got interrupted after a clustering step:

```
Adding seq146 146/147 (99% of total sequences in 144021.971022 secs)
seq144 92%
seq145 15%
seq145 77%
seq145 92%
seq146 9%
seq146 18%
seq146 34%
seq146 56%
Adding seq147 147/147 (100% of total sequences in 144104.317787 secs)
seq146 81%
Candidates: 39227
Clustering
vsearch --cluster_fast results/job/candidates.fasta --threads 4 --strand both --clusters results/job/temp/clust --iddef 1 --id 0.8
Clustering done
Filtering clusters
Initial clusters: 27576
Clusters: 44
144437.917538 secs
Traceback (most recent call last):
  File "/.../miniconda3/envs/transposon_annotation_tools_env/share/TransposonAnnotator_reasonaTE/TransposonAnnotator.py", line 86, in <module>
    runAnnotation(arg1, arg2, arg3, arg4)
  File "/.../miniconda3/envs/transposon_annotation_tools_env/share/TransposonAnnotator_reasonaTE/AnnotationCommander.py", line 150, in runAnnotation
    runMust(projectFolderPath, "")
  File "/.../miniconda3/envs/transposon_annotation_tools_env/share/TransposonAnnotator_reasonaTE/AnnotationCommander.py", line 32, in runMust
    os.mkdir(os.path.join(projectFolderPath,"must","temp"))
OSError: [Errno 17] File exists: '/.../TEpred/TEpred1/must/temp'
```
This problem might come from the fact that I first launched reasonaTE, interrupted it, then relaunched it in the same folder.
Is there any direct way to re-start the pipeline where it stopped? 
The temp folder that causes the problem is empty.

Thanks a lot!

**Comment by DerKevinRiehl** [comment]
Dear Fantin-Mesny,
first of all thank you very much for your interest in using our software.

As we can see based on the error message, the tool "MUSTv2" is causing this error.
This can have multiple reasons that I cant tell, as this software tool was not written by us.

**Suggestion:**
1. Please navigate to the project Folder, then navigate to "must" and empty everything within this folder.
2. Run reasonate with following commands: reasonaTE (-mode checkAnnotations) and provide the list here on Github.
3. In general, as you used "tool all" and you got stuck at must, you still need to annotate with following tools: "must", "repeatmodel", "repMasker", "sinefind", "sinescan", "tirvish", "transposonPSI", "NCBICDD1000".

**Takeaway for the next update of reasonaTE**
Thanks for posting this comment. 
Currently when running annotate with tools all: All tools are rerun.
Possibly for the future: Depending on another flag, provide option to check the ones that were run successfully, and just run the remaining ones. Is this desirable for you?

Best regards,
Kevin Riehl

**Comment by fantin-mesny** [comment]
Dear Kevin,

Many thanks for your reply and your help.
I have relaunched the pipeline with command ```reasonaTE -tool must repeatmodel repMasker sinefind sinescan transposonPSI NCBICDD1000```.

It would indeed be great to have an option allowing to restart the pipeline with only the remaining tools!

Here is the output of reasonaTE -mode checkAnnotations.
```
Checking helitronScanner	... completed
Checking ltrHarvest	... completed
Checking ltrPred	... not completed
Checking mitefind	... completed
Checking mitetracker	... completed
Checking must	... not completed
Checking repeatmodel	... not completed
Checking repMasker	... not completed
Checking sinefind	... not completed
Checking sinescan	... not completed
Checking tirvish	... not completed
Checking transposonPSI	... not completed
Checking NCBICDD1000	... not completed
```
I guess I will have to re-run ltrPred too..

Thanks again, best wishes,

Fantin Mesny

**Comment by DerKevinRiehl** [comment]
Dear Fantin Mesny,
happy to hear back from you.

1) Sorry, you can only run it with one tool at a time. If you write the command that you posted, it will just run it for repeatmodeler.
2) ltrPred is not included in TransposonUltimate / reasonaTE. We managed to package everything into Conda except for ltrPred. If you have a look in the manual, we explain how you can use ltrPred outputs as an input into our pipeline.
3) In general, we offer the possibility to run the different softwares separately so that you can parallelize.
4) Thanks for your feedback. We will include that in the next update of TransposonUltimate / resonaTE.

Please let us know once you finished running all software and if you had any other issues, your feedback helps us to improve our software.

Best regards,
Kevin Riehl
