### ISSUE TITLE
RepeatMasker" and "RepeatModeler

### ISSUE THREAD

**Issue by Ramkyeri** [DerKevinRiehl/transposon_annotation_reasonaTE#9]
Dear Kevin, 

transposon_annotation_reasonaTE is required Python 2.7,  but   RepeatMasker is required Python 3.  

Could you give me some suggestions, 

with regards 

Ramky

![image](https://user-images.githubusercontent.com/70749594/160273515-6181bd69-3029-4794-8c12-7e207f1b566a.png)

**Comment by Ramkyeri** [comment]
Dear Kevin,  

While installing RepeatModeler and RepeatMasker   via conda,   I did not get any error,  shall I continue

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin,  

While running transposon_annotation_reasonaTE,   (Option 2),  I got the following error,     

![image](https://user-images.githubusercontent.com/70749594/160984337-969e435b-21fc-487f-b624-45faed4cc799.png)

However,  RepeatModeler and RepeatMasker did not show any error,  

![image](https://user-images.githubusercontent.com/70749594/160984458-cd05b05b-b850-4482-a7fd-8e88682c8dc8.png)


with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin,  

which one I have to consider as final  GFF3 for RNAseq analysis. 

![image](https://user-images.githubusercontent.com/70749594/160987620-7de50d9b-b16b-474f-83d7-a342d54f7f48.png)

with regards 

Ramky

**Comment by DerKevinRiehl** [comment]
Dear Ramky,
I am happy to see you made a great progress :-).

You can see the meaning of all these files explained in the [tutorial ](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE)under section "Documentation of output files".

What you most probably want is "FinalAnnotations_Transposons".

Please let me know if this was of help.

Best regards,
Kevin

**Comment by DerKevinRiehl** [comment]
Dear Ramky,
did this problem solve already?

_While running transposon_annotation_reasonaTE, (Option 2), I got the following error,_

Best, Kevin

**Comment by Ramkyeri** [comment]
> Dear Ramky, I am happy to see you made a great progress :-).
> 
> You can see the meaning of all these files explained in the [tutorial ](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE)under section "Documentation of output files".
> 
> What you most probably want is "FinalAnnotations_Transposons".
> 
> Please let me know if this was of help.
> 
> Best regards, Kevin

Dear Kevin, 

Thank you very much,  

FinalAnnotations_Transposons has complete information about both DNA and RNA transposons. 

I hope that FinalAnnotations_Transposons is enough.   

If I need any specific analysis, I can use of other GFF files.  

with regards 

Ramky

**Comment by Ramkyeri** [comment]
> Dear Ramky, did this problem solve already?
> 
> _While running transposon_annotation_reasonaTE, (Option 2), I got the following error,_
> 
> Best, Kevin

Dear Kevin,  

Thank you,  Today,  again I run the programme. I got same error, 

I think,    demo.fasta file does not have SINE candidates,    

![image](https://user-images.githubusercontent.com/70749594/161694597-e2dc4f21-4e22-4b27-be45-da85cf5843f1.png)
![image](https://user-images.githubusercontent.com/70749594/161694691-4a666592-c274-4bb3-8f66-36bb413fccd0.png)

with regards
Ramky

**Comment by DerKevinRiehl** [comment]
Dear Ramky,
the tool you are using is sinescan, in your console outputs it even says "2 sequences found", I guess thats not the problem.
At the end, did some files get generated in the folder or not?

If you use the demo.fasta from my tutorial, sine scan should create following files:
https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/tree/main/workspace/testProject/sinescan/result

Did you get similar outputs? Then I guess you can ignore the error messages.

Best regards, Kevin

**Comment by Ramkyeri** [comment]
Dear Kevin, 

Thank you so much. It generated output files,  

![image](https://user-images.githubusercontent.com/70749594/161881515-aa32d154-c42e-4f13-a373-ead6235868ce.png)

RG.error  "Your Genomic dataset has no reasonable SINE candidates under parameters settings of this running round. Please check the logfile inside /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result//RG."


![image](https://user-images.githubusercontent.com/70749594/161881681-78e6a53d-9de4-4cdc-9171-c5f0ad7ee7c3.png)


logfile inside  

Command
/home/ramky/miniconda3/envs/transposon_annotation_tools_env/bin/SINE_Scan-v1.1.1//PL_pipeline/rg_mainscript.pl /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/sequence.sine.fa /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/sequence.fasta 5 /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG 60 25 2

Create working dir: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG

Make directory for each TE:

Check copy number for TE clusters

-----work on cluster 0-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/0
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/0/0.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/0/0.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 0 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 1-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/1
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/1/1.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/1/1.sine.genome.bls
In cycle 0,Find 100 rough good hits with identical percentage more than 80%
Find 35  accurate good hits with 5 side preflank_length=0 bp sequence and 3 side suffixflank_length=60 bp sequence
Extract 35 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/1/1.sine.extendseq

-----work on cluster 2-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/2
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/2/2.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/2/2.sine.genome.bls
In cycle 0,Find 3 rough good hits with identical percentage more than 80%
Cluster 2 has 3 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 3-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/3
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/3/3.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/3/3.sine.genome.bls
In cycle 0,Find 2 rough good hits with identical percentage more than 80%
Cluster 3 has 2 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 4-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/4
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/4/4.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/4/4.sine.genome.bls
In cycle 0,Find 140 rough good hits with identical percentage more than 80%
Find 35  accurate good hits with 5 side preflank_length=0 bp sequence and 3 side suffixflank_length=60 bp sequence
Extract 35 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/4/4.sine.extendseq

-----work on cluster 5-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/5
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/5/5.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/5/5.sine.genome.bls
In cycle 0,Find 78 rough good hits with identical percentage more than 80%
Find 35  accurate good hits with 5 side preflank_length=60 bp sequence and 3 side suffixflank_length=0 bp sequence
Extract 35 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/5/5.sine.extendseq

-----work on cluster 6-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/6
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/6/6.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/6/6.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 6 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 7-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/7
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/7/7.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/7/7.sine.genome.bls
In cycle 0,Find 83 rough good hits with identical percentage more than 80%
Find 35  accurate good hits with 5 side preflank_length=60 bp sequence and 3 side suffixflank_length=0 bp sequence
Extract 35 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/7/7.sine.extendseq

-----work on cluster 8-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/8
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/8/8.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/8/8.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 8 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 9-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/9
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/9/9.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/9/9.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 9 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 10-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/10
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/10/10.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/10/10.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 10 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 11-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/11
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/11/11.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/11/11.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 11 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 12-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/12
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/12/12.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/12/12.sine.genome.bls
In cycle 0,Find 9 rough good hits with identical percentage more than 80%
Find 9  accurate good hits with 5 side preflank_length=60 bp sequence and 3 side suffixflank_length=0 bp sequence
Extract 9 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/12/12.sine.extendseq

-----work on cluster 13-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/13
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/13/13.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/13/13.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 13 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 14-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/14
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/14/14.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/14/14.sine.genome.bls
In cycle 0,Find 2 rough good hits with identical percentage more than 80%
Cluster 14 has 2 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 15-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/15
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/15/15.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/15/15.sine.genome.bls
In cycle 0,Find 2 rough good hits with identical percentage more than 80%
Cluster 15 has 2 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 16-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/16
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/16/16.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/16/16.sine.genome.bls
In cycle 0,Find 2 rough good hits with identical percentage more than 80%
Cluster 16 has 2 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 17-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/17
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/17/17.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/17/17.sine.genome.bls
In cycle 0,Find 8 rough good hits with identical percentage more than 80%
Find 8  accurate good hits with 5 side preflank_length=0 bp sequence and 3 side suffixflank_length=0 bp sequence
Extract 8 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/17/17.sine.extendseq

-----work on cluster 18-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/18
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/18/18.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/18/18.sine.genome.bls
In cycle 0,Find 9 rough good hits with identical percentage more than 80%
Find 9  accurate good hits with 5 side preflank_length=60 bp sequence and 3 side suffixflank_length=60 bp sequence
Extract 9 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/18/18.sine.extendseq

-----work on cluster 19-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/19
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/19/19.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/19/19.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 19 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 20-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/20
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/20/20.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/20/20.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 20 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 21-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/21
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/21/21.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/21/21.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 21 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 22-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/22
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/22/22.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/22/22.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 22 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 23-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/23
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/23/23.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/23/23.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 23 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 24-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/24
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/24/24.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/24/24.sine.genome.bls
In cycle 0,Find 2 rough good hits with identical percentage more than 80%
Cluster 24 has 2 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 25-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/25
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/25/25.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/25/25.sine.genome.bls
In cycle 0,Find 80 rough good hits with identical percentage more than 80%
Find 35  accurate good hits with 5 side preflank_length=60 bp sequence and 3 side suffixflank_length=0 bp sequence
Extract 35 best hits: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/25/25.sine.extendseq

-----work on cluster 26-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/26
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/26/26.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/26/26.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 26 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

-----work on cluster 27-----
Its path is: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/27
TE sequence: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/27/27.sine.fa
Scan genome using a file above: /mnt/e/TransposonUltimate/workspace/testProject/sinescan/result/RG/27/27.sine.genome.bls
In cycle 0,Find 1 rough good hits with identical percentage more than 80%
Cluster 27 has 1 good hits in genome, less than the cutoff value 5: stop analyse this cluster!

Done.


with regards 

Ramky

**Comment by DerKevinRiehl** [comment]
That is really not an expected behavior...

maybe you can try to get the software running yourself based on the advise of the authors...
https://github.com/maohlzj/SINE_Scan

... and then copy the generated output files to the reasonaTE project folder...
(take care they are called sequence, like in the example:)
https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/tree/main/workspace/testProject/sinescan/result

**Comment by Ramkyeri** [comment]
Dear Kevin.  

Many thanks for your suggestion. 

with regards

Ramky
